#!/bin/bash


val=256
d1=16
d2=16

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done

val=512
d1=32
d2=16

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done

val=1024
d1=32
d2=32

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done

val=2048
d1=64
d2=32

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done

val=4096
d1=64
d2=64

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done

val=8192
d1=128
d2=64

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done

val=16384
d1=128
d2=128

mkdir impl_p$val
cp compile impl_p$val

for i in `ls *.query`
do
	sed -e "s/DISTMAT1/$d1/g;s/DISTMAT2/$d2/g;s/DISTVECT/$val/g" $i > impl_p$val/$i
done