#!/bin/sh

hometmp=$(pwd)

rm -r /gpfsdata/jgurhem/test_xmp/impl/impl_size*

cd /gpfsdata/jgurhem/test_xmp/impl/impl_SIZE
./changesize 4

cd ../impl_size4
./changep 4 2 2

cd impl_p4/
#./compile
#yml_component --force XMP_prodMat.query
yml_component --force XMP_prodMat3.query
yml_component --force XMP_prodMat4.query

cd $hometmp

yml_compiler testProdMat.query 

omrpc-register-yml testProdMat.query.yapp | grep ^testProdMat > stubs
echo " " >> stubs
cp stubs  ~/.omrpc_registry
cp hosts ~/.omrpc_registry/nodes
#cp mpi.xcf ../../etc/yml/
#cat stubs
#echo "mpirun -n 1 -machinefile ./hosts yml_scheduler gaussJordan.query.yapp"
