#!/bin/sh
file=$1

nbWorker=0
tmpGen=0
totGen=0
tmpNoG=0
totNoG=0
nbTask=0

nbWorker=$(grep pid=* $file | cut -d '(' -f2 | sort | uniq -c | wc -l)
tmpGen=$(grep -E "start *|end *" $file -A 1 | grep -e '(' | cut -d '(' -f2 | tr -d ')' | awk '{x[NR]=$1}END{asort(x);print x[NR]-x[1]}')
totGen=$(grep elasped* $file | grep time: | cut -d ' ' -f3 | awk '{s+=$1} END {print s}')
tmpNoG=$(grep -v ^host $file | sed -E '/genMat|fillMatrixZero|genVect/,+9d' | grep -E "start *|end *" -A 1 | grep -e '(' | cut -d '(' -f2 | tr -d ')' | awk '{x[NR]=$1}END{asort(x);print x[NR]-x[1]}')
totNoG=$(grep -v ^host $file | sed -E '/genMat|fillMatrixZero|genVect/,+9d' | grep elasped* | grep time: | cut -d ' ' -f3 | awk '{s+=$1} END {print s}')
nbTask=$(grep -c SUCCESS $file)
