#!/bin/bash

file=$1
declare -a myArray

myArray=($(grep pid=* $file | cut -d '(' -f2 | sort | uniq -c | tr -d ')' | cut -d= -f2))

for i in "${myArray[@]}"
do
	echo "pid $i"; 
	grep -v ^host $file | grep pid=$i -A 7 | grep time: | cut -d ' ' -f3 | awk '{s+=$1} END {print s}';
	echo " ";
done

echo "total use";
grep elasped* $file | grep time: | cut -d ' ' -f3 | awk '{s+=$1} END {print s}';

echo "temps exec";
grep -E "start *|end *" $file -A 1 | grep -e '(' | cut -d '(' -f2 | tr -d ')' | awk '{x[NR]=$1}END{asort(x);print "t= "x[NR]-x[1]}';

